name = "yumikokawaii/plutus_v3"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'yumikokawaii/plutus_v3'"

[repository]
user = "yumikokawaii"
project = "plutus_v3"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
